package dev.syncended.whois

object TldUtils {
    private val TopLevelDomain.nicServer: String
        get() = "whois.nic.${tldName}"

    @JvmStatic
    fun decodeFromDomain(rawUrl: String): TopLevelDomain? {
        val lowerUrl = rawUrl.lowercase()
        return TopLevelDomain.entries.find { lowerUrl.endsWith(it.tldName) }
    }

    @JvmStatic
    fun getWhoisServer(tld: TopLevelDomain): String {
        return when(tld) {
            // TLD servers
            TopLevelDomain.MIL -> TODO()
            TopLevelDomain.IN_ADDR_ARPA -> TODO()
            TopLevelDomain.IP6_ARPA -> TODO()
            TopLevelDomain.AD -> TODO()
            TopLevelDomain.AL -> TODO()
            TopLevelDomain.AO -> TODO()
            TopLevelDomain.AQ -> TODO()
            TopLevelDomain.GOV_AZ -> TODO()
            TopLevelDomain.AZ -> TODO()
            TopLevelDomain.BA -> TODO()
            TopLevelDomain.BB -> TODO()
            TopLevelDomain.BD -> TODO()
            TopLevelDomain.BS -> TODO()
            TopLevelDomain.BT -> TODO()
            TopLevelDomain.BV -> TODO()
            TopLevelDomain.CF -> TODO()
            TopLevelDomain.CG -> TODO()
            TopLevelDomain.CK -> TODO()
            TopLevelDomain.CU -> TODO()
            TopLevelDomain.CW -> TODO()
            TopLevelDomain.CY -> TODO()
            TopLevelDomain.DJ -> TODO()
            TopLevelDomain.EG -> TODO()
            TopLevelDomain.ER -> TODO()
            TopLevelDomain.ES -> TODO()
            TopLevelDomain.ET -> TODO()
            TopLevelDomain.FK -> TODO()
            TopLevelDomain.GB -> TODO()
            TopLevelDomain.GM -> TODO()
            TopLevelDomain.GR -> TODO()
            TopLevelDomain.GT -> TODO()
            TopLevelDomain.GU -> TODO()
            TopLevelDomain.GW -> TODO()
            TopLevelDomain.JM -> TODO()
            TopLevelDomain.JO -> TODO()
            TopLevelDomain.KH -> TODO()
            TopLevelDomain.KM -> TODO()
            TopLevelDomain.KP -> TODO()
            TopLevelDomain.LR -> TODO()
            TopLevelDomain.MC -> TODO()
            TopLevelDomain.MH -> TODO()
            TopLevelDomain.MO -> TODO()
            TopLevelDomain.MP -> TODO()
            TopLevelDomain.MV -> TODO()
            TopLevelDomain.NE -> TODO()
            TopLevelDomain.NI -> TODO()
            TopLevelDomain.NP -> TODO()
            TopLevelDomain.NR -> TODO()
            TopLevelDomain.PA -> TODO()
            TopLevelDomain.PG -> TODO()
            TopLevelDomain.EDU_PH -> TODO()
            TopLevelDomain.GOV_PH -> TODO()
            TopLevelDomain.PH -> TODO()
            TopLevelDomain.PN -> TODO()
            TopLevelDomain.PY -> TODO()
            TopLevelDomain.SJ -> TODO()
            TopLevelDomain.SR -> TODO()
            TopLevelDomain.SV -> TODO()
            TopLevelDomain.SZ -> TODO()
            TopLevelDomain.TJ -> TODO()
            TopLevelDomain.TT -> TODO()
            TopLevelDomain.BL_UK -> TODO()
            TopLevelDomain.BRITISH_LIBRARY_UK -> TODO()
            TopLevelDomain.ICNET_UK -> TODO()
            TopLevelDomain.JET_UK -> TODO()
            TopLevelDomain.MOD_UK -> TODO()
            TopLevelDomain.NHS_UK -> TODO()
            TopLevelDomain.NLS_UK -> TODO()
            TopLevelDomain.PARLIAMENT_UK -> TODO()
            TopLevelDomain.POLICE_UK -> TODO()
            TopLevelDomain.EDU_UY -> TODO()
            TopLevelDomain.GUB_UY -> TODO()
            TopLevelDomain.MIL_UY -> TODO()
            TopLevelDomain.NET_UY -> TODO()
            TopLevelDomain.ORG_UY -> TODO()
            TopLevelDomain.UY -> TODO()
            TopLevelDomain.VA -> TODO()
            TopLevelDomain.VN -> TODO()
            TopLevelDomain.ALT_ZA -> TODO()
            TopLevelDomain.EDU_ZA -> TODO()
            TopLevelDomain.ZA -> TODO()
            TopLevelDomain.ZW -> TODO()
            TopLevelDomain.XN__54B7FTA0CC -> TODO()
            TopLevelDomain.XN__L1ACC -> TODO()
            TopLevelDomain.XN__MGBAI9AZGQP6J -> TODO()
            TopLevelDomain.XN__MGBAYH7GPA -> TODO()
            TopLevelDomain.XN__MGBC0A9AZCG -> TODO()
            TopLevelDomain.XN__MGBCPQ6GPA1A -> TODO()
            TopLevelDomain.XN__MGBPL2FH -> TODO()
            TopLevelDomain.XN__MIX891F -> TODO()
            TopLevelDomain.XN__QXAM -> TODO()
            TopLevelDomain.BR_COM -> "whois.centralnic.net"
            TopLevelDomain.CN_COM -> "whois.centralnic.net"
            TopLevelDomain.DE_COM -> "whois.centralnic.net"
            TopLevelDomain.EU_COM -> "whois.centralnic.net"
            TopLevelDomain.GB_COM -> "whois.centralnic.net"
            TopLevelDomain.GB_NET -> "whois.centralnic.net"
            TopLevelDomain.GR_COM -> "whois.centralnic.net"
            TopLevelDomain.HU_COM -> "whois.centralnic.net"
            TopLevelDomain.IN_NET -> "whois.centralnic.net"
            TopLevelDomain.NO_COM -> "whois.centralnic.net"
            TopLevelDomain.QC_COM -> "whois.centralnic.net"
            TopLevelDomain.RU_COM -> "whois.centralnic.net"
            TopLevelDomain.SA_COM -> "whois.centralnic.net"
            TopLevelDomain.SE_COM -> "whois.centralnic.net"
            TopLevelDomain.SE_NET -> "whois.centralnic.net"
            TopLevelDomain.UK_COM -> "whois.centralnic.net"
            TopLevelDomain.UK_NET -> "whois.centralnic.net"
            TopLevelDomain.US_COM -> "whois.centralnic.net"
            TopLevelDomain.UY_COM -> "whois.centralnic.net"
            TopLevelDomain.ZA_COM -> "whois.centralnic.net"
            TopLevelDomain.JPN_COM -> "whois.centralnic.net"
            TopLevelDomain.WEB_COM -> "whois.centralnic.net"
            TopLevelDomain.COM -> "whois.verisign-grs.com"
            TopLevelDomain.ZA_NET -> "whois.za.net"
            TopLevelDomain.NET -> "whois.verisign-grs.com"
            TopLevelDomain.EU_ORG -> "whois.eu.org"
            TopLevelDomain.ZA_ORG -> "whois.za.org"
            TopLevelDomain.ORG -> "whois.pir.org"
            TopLevelDomain.LLYW_CYMRU -> "whois.nic.llyw.cymru"
            TopLevelDomain.GOV_SCOT -> "whois.nic.gov.scot"
            TopLevelDomain.GOV_WALES -> "whois.nic.gov.wales"
            TopLevelDomain.EDU -> "whois.educause.edu"
            TopLevelDomain.GOV -> "whois.dotgov.gov"
            TopLevelDomain.INT -> "whois.iana.org"
            TopLevelDomain.E164_ARPA -> "whois.ripe.net"
            TopLevelDomain.ARPA -> "whois.iana.org"
            TopLevelDomain.AERO -> "whois.aero"
            TopLevelDomain.ASIA -> "whois.nic.asia"
            TopLevelDomain.BIZ -> "whois.nic.biz"
            TopLevelDomain.CAT -> "whois.nic.cat"
            TopLevelDomain.COOP -> "whois.nic.coop"
            TopLevelDomain.INFO -> "whois.afilias.net"
            TopLevelDomain.JOBS -> "whois.nic.jobs"
            TopLevelDomain.MOBI -> "whois.afilias.net"
            TopLevelDomain.MUSEUM -> "whois.nic.museum"
            TopLevelDomain.NAME -> "whois.nic.name"
            TopLevelDomain.POST -> "whois.dotpostregistry.net"
            TopLevelDomain.PRO -> "whois.nic.pro"
            TopLevelDomain.TEL -> "whois.nic.tel"
            TopLevelDomain.TRAVEL -> "whois.nic.travel"
            TopLevelDomain.XXX -> "whois.nic.xxx"
            TopLevelDomain.AC -> "whois.nic.ac"
            TopLevelDomain.AE -> "whois.aeda.net.ae"
            TopLevelDomain.AF -> "whois.nic.af"
            TopLevelDomain.AG -> "whois.nic.ag"
            TopLevelDomain.AI -> "whois.nic.ai"
            TopLevelDomain.AM -> "whois.amnic.net"
            TopLevelDomain.AR -> "whois.nic.ar"
            TopLevelDomain.AS -> "whois.nic.as"
            TopLevelDomain.PRIV_AT -> "whois.nic.priv.at"
            TopLevelDomain.AT -> "whois.nic.at"
            TopLevelDomain.AU -> "whois.auda.org.au"
            TopLevelDomain.AW -> "whois.nic.aw"
            TopLevelDomain.AX -> "whois.ax"
            TopLevelDomain.BE -> "whois.dns.be"
            TopLevelDomain.BF -> "whois.registre.bf"
            TopLevelDomain.BG -> "whois.register.bg"
            TopLevelDomain.BH -> "whois.nic.bh"
            TopLevelDomain.BI -> "whois1.nic.bi"
            TopLevelDomain.BJ -> "whois.nic.bj"
            TopLevelDomain.BM -> "whois.nic.bm"
            TopLevelDomain.BN -> "whois.bnnic.bn"
            TopLevelDomain.BO -> "whois.nic.bo"
            TopLevelDomain.BR -> "whois.registro.br"
            TopLevelDomain.BY -> "whois.cctld.by"
            TopLevelDomain.BW -> "whois.nic.net.bw"
            TopLevelDomain.BZ -> "RECURSIVE"
            TopLevelDomain.CO_CA -> "whois.co.ca"
            TopLevelDomain.CA -> "whois.cira.ca"
            TopLevelDomain.CC -> "VERISIGN"
            TopLevelDomain.CD -> "whois.nic.cd"
            TopLevelDomain.CH -> "whois.nic.ch"
            TopLevelDomain.CI -> "whois.nic.ci"
            TopLevelDomain.CL -> "whois.nic.cl"
            TopLevelDomain.CM -> "whois.netcom.cm"
            TopLevelDomain.EDU_CN -> "whois.edu.cn"
            TopLevelDomain.CN -> "whois.cnnic.cn"
            TopLevelDomain.UK_CO -> "whois.uk.co"
            TopLevelDomain.CO -> "whois.nic.co"
            TopLevelDomain.CR -> "whois.nic.cr"
            TopLevelDomain.CV -> "whois.nic.cv"
            TopLevelDomain.CX -> "whois.nic.cx"
            TopLevelDomain.CZ -> "whois.nic.cz"
            TopLevelDomain.DE -> "whois.denic.de"
            TopLevelDomain.DK -> "whois.punktum.dk"
            TopLevelDomain.DM -> "whois.dmdomains.dm"
            TopLevelDomain.DO -> "whois.nic.do"
            TopLevelDomain.DZ -> "whois.nic.dz"
            TopLevelDomain.EC -> "whois.nic.ec"
            TopLevelDomain.EE -> "whois.tld.ee"
            TopLevelDomain.EU -> "whois.eu"
            TopLevelDomain.FI -> "whois.fi"
            TopLevelDomain.FJ -> "www.whois.fj"
            TopLevelDomain.FM -> "whois.nic.fm"
            TopLevelDomain.FO -> "whois.nic.fo"
            TopLevelDomain.FR -> "whois.nic.fr"
            TopLevelDomain.GA -> "whois.nic.ga"
            TopLevelDomain.GD -> "whois.nic.gd"
            TopLevelDomain.GE -> "whois.nic.ge"
            TopLevelDomain.GF -> "whois.mediaserv.net"
            TopLevelDomain.GG -> "whois.gg"
            TopLevelDomain.GH -> "whois.nic.gh"
            TopLevelDomain.GI -> "whois2.afilias-grs.net"
            TopLevelDomain.GL -> "whois.nic.gl"
            TopLevelDomain.GN -> "whois.ande.gov.gn"
            TopLevelDomain.GP -> "whois.nic.gp"
            TopLevelDomain.GQ -> "whois.dominio.gq"
            TopLevelDomain.GS -> "whois.nic.gs"
            TopLevelDomain.GY -> "whois.registry.gy"
            TopLevelDomain.HK -> "whois.hkirc.hk"
            TopLevelDomain.HM -> "whois.registry.hm"
            TopLevelDomain.HN -> "whois.nic.hn"
            TopLevelDomain.HR -> "whois.dns.hr"
            TopLevelDomain.HT -> "whois.nic.ht"
            TopLevelDomain.HU -> "whois.nic.hu"
            TopLevelDomain.ID -> "whois.id"
            TopLevelDomain.IE -> "whois.weare.ie"
            TopLevelDomain.IL -> "whois.isoc.org.il"
            TopLevelDomain.IM -> "whois.nic.im"
            TopLevelDomain.IN -> "whois.registry.in"
            TopLevelDomain.IO -> "whois.nic.io"
            TopLevelDomain.IQ -> "whois.cmc.iq"
            TopLevelDomain.IR -> "whois.nic.ir"
            TopLevelDomain.IS -> "whois.isnic.is"
            TopLevelDomain.IT -> "whois.nic.it"
            TopLevelDomain.JE -> "whois.je"
            TopLevelDomain.JP -> "whois.jprs.jp"
            TopLevelDomain.KE -> "whois.kenic.or.ke"
            TopLevelDomain.KG -> "whois.kg"
            TopLevelDomain.KI -> "whois.nic.ki"
            TopLevelDomain.KN -> "whois.nic.kn"
            TopLevelDomain.KR -> "whois.kr"
            TopLevelDomain.KW -> "whois.nic.kw"
            TopLevelDomain.KY -> "whois.kyregistry.ky"
            TopLevelDomain.KZ -> "whois.nic.kz"
            TopLevelDomain.LA -> "whois.nic.la"
            TopLevelDomain.LB -> "whois.lbdr.org.lb"
            TopLevelDomain.LC -> "whois2.afilias-grs.net"
            TopLevelDomain.LI -> "whois.nic.li"
            TopLevelDomain.LK -> "whois.nic.lk"
            TopLevelDomain.LS -> "whois.nic.ls"
            TopLevelDomain.LT -> "whois.domreg.lt"
            TopLevelDomain.LU -> "whois.dns.lu"
            TopLevelDomain.LV -> "whois.nic.lv"
            TopLevelDomain.LY -> "whois.nic.ly"
            TopLevelDomain.MA -> "whois.registre.ma"
            TopLevelDomain.MD -> "whois.nic.md"
            TopLevelDomain.ME -> "whois.nic.me"
            TopLevelDomain.MG -> "whois.nic.mg"
            TopLevelDomain.MK -> "whois.marnet.mk"
            TopLevelDomain.ML -> "whois.nic.ml"
            TopLevelDomain.MM -> "whois.registry.gov.mm"
            TopLevelDomain.MN -> "whois.nic.mn"
            TopLevelDomain.MQ -> "whois.mediaserv.net"
            TopLevelDomain.MR -> "whois.nic.mr"
            TopLevelDomain.MS -> "whois.nic.ms"
            TopLevelDomain.MT -> "whois.nic.org.mt"
            TopLevelDomain.MU -> "whois.nic.mu"
            TopLevelDomain.MW -> "whois.nic.mw"
            TopLevelDomain.MX -> "whois.mx"
            TopLevelDomain.MY -> "whois.mynic.my"
            TopLevelDomain.MZ -> "whois.nic.mz"
            TopLevelDomain.NA -> "whois.na-nic.com.na"
            TopLevelDomain.NC -> "whois.nc"
            TopLevelDomain.NF -> "whois.nic.nf"
            TopLevelDomain.NG -> "whois.nic.net.ng"
            TopLevelDomain.NL -> "whois.domain-registry.nl"
            TopLevelDomain.NO -> "whois.norid.no"
            TopLevelDomain.NU -> "whois.iis.nu"
            TopLevelDomain.NZ -> "whois.irs.net.nz"
            TopLevelDomain.OM -> "whois.registry.om"
            TopLevelDomain.PE -> "kero.yachay.pe"
            TopLevelDomain.PF -> "whois.registry.pf"
            TopLevelDomain.PK -> "whois.pknic.net.pk"
            TopLevelDomain.CO_PL -> "whois.co.pl"
            TopLevelDomain.PL -> "whois.dns.pl"
            TopLevelDomain.PM -> "whois.nic.pm"
            TopLevelDomain.PR -> "whois.afilias-srs.net"
            TopLevelDomain.PS -> "whois.pnina.ps"
            TopLevelDomain.PT -> "whois.dns.pt"
            TopLevelDomain.PW -> "whois.nic.pw"
            TopLevelDomain.QA -> "whois.registry.qa"
            TopLevelDomain.RE -> "whois.nic.re"
            TopLevelDomain.RO -> "whois.rotld.ro"
            TopLevelDomain.RS -> "whois.rnids.rs"
            TopLevelDomain.AC_RU -> "whois.free.net"
            TopLevelDomain.EDU_RU -> "whois.informika.ru"
            TopLevelDomain.COM_RU -> "whois.flexireg.net"
            TopLevelDomain.MSK_RU -> "whois.flexireg.net"
            TopLevelDomain.NET_RU -> "whois.nic.net.ru"
            TopLevelDomain.NOV_RU -> "whois.flexireg.net"
            TopLevelDomain.ORG_RU -> "whois.nic.net.ru"
            TopLevelDomain.PP_RU -> "whois.nic.net.ru"
            TopLevelDomain.SPB_RU -> "whois.flexireg.net"
            TopLevelDomain.RU -> "whois.tcinet.ru"
            TopLevelDomain.RW -> "whois.ricta.org.rw"
            TopLevelDomain.SA -> "whois.nic.net.sa"
            TopLevelDomain.SB -> "whois.nic.net.sb"
            TopLevelDomain.SC -> "whois.nic.sc"
            TopLevelDomain.SD -> "whois.nic.sd"
            TopLevelDomain.SE -> "whois.iis.se"
            TopLevelDomain.SG -> "whois.sgnic.sg"
            TopLevelDomain.SH -> "whois.nic.sh"
            TopLevelDomain.SI -> "whois.register.si"
            TopLevelDomain.SK -> "whois.sk-nic.sk"
            TopLevelDomain.SL -> "whois.nic.sl"
            TopLevelDomain.SM -> "whois.nic.sm"
            TopLevelDomain.SN -> "whois.nic.sn"
            TopLevelDomain.SO -> "whois.nic.so"
            TopLevelDomain.SS -> "whois.nic.ss"
            TopLevelDomain.ST -> "whois.nic.st"
            TopLevelDomain.MSK_SU -> "whois.flexireg.net"
            TopLevelDomain.NOV_SU -> "whois.flexireg.net"
            TopLevelDomain.SPB_SU -> "whois.flexireg.net"
            TopLevelDomain.SU -> "whois.tcinet.ru"
            TopLevelDomain.SX -> "whois.sx"
            TopLevelDomain.SY -> "whois.tld.sy"
            TopLevelDomain.TC -> "whois.nic.tc"
            TopLevelDomain.TD -> "whois.nic.td"
            TopLevelDomain.TF -> "whois.nic.tf"
            TopLevelDomain.TG -> "whois.nic.tg"
            TopLevelDomain.TH -> "whois.thnic.co.th"
            TopLevelDomain.TK -> "whois.dot.tk"
            TopLevelDomain.TL -> "whois.nic.tl"
            TopLevelDomain.TM -> "whois.nic.tm"
            TopLevelDomain.TN -> "whois.ati.tn"
            TopLevelDomain.TO -> "whois.tonic.to"
            TopLevelDomain.TR -> "whois.trabis.gov.tr"
            TopLevelDomain.TV -> "RECURSIVE"
            TopLevelDomain.TW -> "whois.twnic.net.tw"
            TopLevelDomain.TZ -> "whois.tznic.or.tz"
            TopLevelDomain.BIZ_UA -> "whois.biz.ua"
            TopLevelDomain.CO_UA -> "whois.co.ua"
            TopLevelDomain.PP_UA -> "whois.pp.ua"
            TopLevelDomain.UA -> "whois.ua"
            TopLevelDomain.UG -> "whois.co.ug"
            TopLevelDomain.AC_UK -> "whois.nic.ac.uk"
            TopLevelDomain.GOV_UK -> "whois.gov.uk"
            TopLevelDomain.UK -> "whois.nic.uk"
            TopLevelDomain.FED_US -> "whois.nic.gov"
            TopLevelDomain.US -> "whois.nic.us"
            TopLevelDomain.UZ -> "whois.cctld.uz"
            TopLevelDomain.VC -> "whois2.afilias-grs.net"
            TopLevelDomain.VE -> "whois.nic.ve"
            TopLevelDomain.VG -> "whois.nic.vg"
            TopLevelDomain.VI -> "whois.nic.vi"
            TopLevelDomain.VU -> "whois.dnrs.vu"
            TopLevelDomain.WF -> "whois.nic.wf"
            TopLevelDomain.WS -> "whois.website.ws"
            TopLevelDomain.YE -> "whois.y.net.ye"
            TopLevelDomain.YT -> "whois.nic.yt"
            TopLevelDomain.AC_ZA -> "whois.ac.za"
            TopLevelDomain.CO_ZA -> "whois.registry.net.za"
            TopLevelDomain.GOV_ZA -> "whois.gov.za"
            TopLevelDomain.NET_ZA -> "net-whois.registry.net.za"
            TopLevelDomain.ORG_ZA -> "org-whois.registry.net.za"
            TopLevelDomain.WEB_ZA -> "web-whois.registry.net.za"
            TopLevelDomain.ZM -> "whois.zicta.zm"
            TopLevelDomain.XN__2SCRJ9C -> "whois.registry.in"
            TopLevelDomain.XN__3E0B707E -> "whois.kr"
            TopLevelDomain.XN__3HCRJ9C -> "whois.registry.in"
            TopLevelDomain.XN__45BR5CYL -> "whois.registry.in"
            TopLevelDomain.XN__45BRJ9C -> "whois.registry.in"
            TopLevelDomain.XN__4DBRK0CE -> "whois.isoc.org.il"
            TopLevelDomain.XN__80AO21A -> "whois.nic.kz"
            TopLevelDomain.XN__90A3AC -> "whois.rnids.rs"
            TopLevelDomain.XN__90AE -> "whois.imena.bg"
            TopLevelDomain.XN__90AIS -> "whois.cctld.by"
            TopLevelDomain.XN__CLCHC0EA0B2G2A9GCD -> "whois.ta.sgnic.sg"
            TopLevelDomain.XN__D1ALF -> "whois.marnet.mk"
            TopLevelDomain.XN__E1A4C -> "whois.eu"
            TopLevelDomain.XN__FIQS8S -> "cwhois.cnnic.cn"
            TopLevelDomain.XN__FIQZ9S -> "cwhois.cnnic.cn"
            TopLevelDomain.XN__FPCRJ9C3D -> "whois.registry.in"
            TopLevelDomain.XN__FZC2C9E2C -> "whois.nic.lk"
            TopLevelDomain.XN__GECRJ9C -> "whois.registry.in"
            TopLevelDomain.XN__H2BREG3EVE -> "whois.registry.in"
            TopLevelDomain.XN__H2BRJ9C8C -> "whois.registry.in"
            TopLevelDomain.XN__H2BRJ9C -> "whois.registry.in"
            TopLevelDomain.XN__J1AMH -> "whois.dotukr.com"
            TopLevelDomain.XN__J6W193G -> "whois.hkirc.hk"
            TopLevelDomain.XN__KPRW13D -> "whois.twnic.net.tw"
            TopLevelDomain.XN__KPRY57D -> "whois.twnic.net.tw"
            TopLevelDomain.XN__LGBBAT1AD8J -> "whois.nic.dz"
            TopLevelDomain.XN__MGB9AWBF -> "whois.registry.om"
            TopLevelDomain.XN__MGBA3A4F16A -> "whois.nic.ir"
            TopLevelDomain.XN__MGBAAM7A8H -> "whois.aeda.net.ae"
            TopLevelDomain.XN__MGBAH1A3HJKRD -> "whois.nic.mr"
            TopLevelDomain.XN__MGBBH1A71E -> "whois.registry.in"
            TopLevelDomain.XN__MGBBH1A -> "whois.registry.in"
            TopLevelDomain.XN__MGBERP4A5D4AR -> "whois.nic.net.sa"
            TopLevelDomain.XN__MGBGU82A -> "whois.registry.in"
            TopLevelDomain.XN__MGBTX2B -> "whois.cmc.iq"
            TopLevelDomain.XN__MGBX4CD0AB -> "whois.mynic.my"
            TopLevelDomain.XN__NODE -> "whois.itdc.ge"
            TopLevelDomain.XN__O3CW4H -> "whois.thnic.co.th"
            TopLevelDomain.XN__OGBPF8FL -> "whois.tld.sy"
            TopLevelDomain.XN__P1AI -> "whois.tcinet.ru"
            TopLevelDomain.XN__PGBS0DH -> "whois.ati.tn"
            TopLevelDomain.XN__Q7CE6A -> "whois.nic.la"
            TopLevelDomain.XN__QXA6A -> "whois.eu"
            TopLevelDomain.XN__RVC1E0AM3E -> "whois.registry.in"
            TopLevelDomain.XN__S9BRJ9C -> "whois.registry.in"
            TopLevelDomain.XN__WGBH1C -> "whois.dotmasr.eg"
            TopLevelDomain.XN__WGBL6A -> "whois.registry.qa"
            TopLevelDomain.XN__XKC2AL3HYE2A -> "whois.nic.lk"
            TopLevelDomain.XN__XKC2DL3A5EE0H -> "whois.registry.in"
            TopLevelDomain.XN__Y9A3AQ -> "whois.amnic.net"
            TopLevelDomain.XN__YFRO4I67O -> "whois.zh.sgnic.sg"
            TopLevelDomain.XN__YGBI2AMMX -> "whois.pnina.ps"

            TopLevelDomain.AAA -> tld.nicServer
            TopLevelDomain.AARP -> tld.nicServer
            TopLevelDomain.ABB -> tld.nicServer
            TopLevelDomain.ABBOTT -> tld.nicServer
            TopLevelDomain.ABBVIE -> tld.nicServer
            TopLevelDomain.ABC -> tld.nicServer
            TopLevelDomain.ABLE -> tld.nicServer
            TopLevelDomain.ABOGADO -> tld.nicServer
            TopLevelDomain.ABUDHABI -> tld.nicServer
            TopLevelDomain.ACADEMY -> tld.nicServer
            TopLevelDomain.ACCENTURE -> tld.nicServer
            TopLevelDomain.ACCOUNTANT -> tld.nicServer
            TopLevelDomain.ACCOUNTANTS -> tld.nicServer
            TopLevelDomain.ACO -> tld.nicServer
            TopLevelDomain.ACTOR -> tld.nicServer
            TopLevelDomain.ADS -> tld.nicServer
            TopLevelDomain.ADULT -> tld.nicServer
            TopLevelDomain.AEG -> tld.nicServer
            TopLevelDomain.AETNA -> tld.nicServer
            TopLevelDomain.AFL -> tld.nicServer
            TopLevelDomain.AFRICA -> tld.nicServer
            TopLevelDomain.AGAKHAN -> tld.nicServer
            TopLevelDomain.AGENCY -> tld.nicServer
            TopLevelDomain.AIG -> tld.nicServer
            TopLevelDomain.AIRBUS -> tld.nicServer
            TopLevelDomain.AIRFORCE -> tld.nicServer
            TopLevelDomain.AIRTEL -> tld.nicServer
            TopLevelDomain.AKDN -> tld.nicServer
            TopLevelDomain.ALIBABA -> tld.nicServer
            TopLevelDomain.ALIPAY -> tld.nicServer
            TopLevelDomain.ALLFINANZ -> tld.nicServer
            TopLevelDomain.ALLSTATE -> tld.nicServer
            TopLevelDomain.ALLY -> tld.nicServer
            TopLevelDomain.ALSACE -> tld.nicServer
            TopLevelDomain.ALSTOM -> tld.nicServer
            TopLevelDomain.AMAZON -> tld.nicServer
            TopLevelDomain.AMERICANEXPRESS -> tld.nicServer
            TopLevelDomain.AMERICANFAMILY -> tld.nicServer
            TopLevelDomain.AMEX -> tld.nicServer
            TopLevelDomain.AMFAM -> tld.nicServer
            TopLevelDomain.AMICA -> tld.nicServer
            TopLevelDomain.AMSTERDAM -> tld.nicServer
            TopLevelDomain.ANALYTICS -> tld.nicServer
            TopLevelDomain.ANDROID -> tld.nicServer
            TopLevelDomain.ANQUAN -> tld.nicServer
            TopLevelDomain.ANZ -> tld.nicServer
            TopLevelDomain.AOL -> tld.nicServer
            TopLevelDomain.APARTMENTS -> tld.nicServer
            TopLevelDomain.APP -> tld.nicServer
            TopLevelDomain.APPLE -> tld.nicServer
            TopLevelDomain.AQUARELLE -> tld.nicServer
            TopLevelDomain.ARAB -> tld.nicServer
            TopLevelDomain.ARAMCO -> tld.nicServer
            TopLevelDomain.ARCHI -> tld.nicServer
            TopLevelDomain.ARMY -> tld.nicServer
            TopLevelDomain.ART -> tld.nicServer
            TopLevelDomain.ARTE -> tld.nicServer
            TopLevelDomain.ASDA -> tld.nicServer
            TopLevelDomain.ASSOCIATES -> tld.nicServer
            TopLevelDomain.ATHLETA -> tld.nicServer
            TopLevelDomain.ATTORNEY -> tld.nicServer
            TopLevelDomain.AUCTION -> tld.nicServer
            TopLevelDomain.AUDI -> tld.nicServer
            TopLevelDomain.AUDIBLE -> tld.nicServer
            TopLevelDomain.AUDIO -> tld.nicServer
            TopLevelDomain.AUSPOST -> tld.nicServer
            TopLevelDomain.AUTHOR -> tld.nicServer
            TopLevelDomain.AUTO -> tld.nicServer
            TopLevelDomain.AUTOS -> tld.nicServer
            TopLevelDomain.AWS -> tld.nicServer
            TopLevelDomain.AXA -> tld.nicServer
            TopLevelDomain.AZURE -> tld.nicServer
            TopLevelDomain.BABY -> tld.nicServer
            TopLevelDomain.BAIDU -> tld.nicServer
            TopLevelDomain.BANAMEX -> tld.nicServer
            TopLevelDomain.BAND -> tld.nicServer
            TopLevelDomain.BANK -> tld.nicServer
            TopLevelDomain.BAR -> tld.nicServer
            TopLevelDomain.BARCELONA -> tld.nicServer
            TopLevelDomain.BARCLAYCARD -> tld.nicServer
            TopLevelDomain.BARCLAYS -> tld.nicServer
            TopLevelDomain.BAREFOOT -> tld.nicServer
            TopLevelDomain.BARGAINS -> tld.nicServer
            TopLevelDomain.BASEBALL -> tld.nicServer
            TopLevelDomain.BASKETBALL -> tld.nicServer
            TopLevelDomain.BAUHAUS -> tld.nicServer
            TopLevelDomain.BAYERN -> tld.nicServer
            TopLevelDomain.BBC -> tld.nicServer
            TopLevelDomain.BBT -> tld.nicServer
            TopLevelDomain.BBVA -> tld.nicServer
            TopLevelDomain.BCG -> tld.nicServer
            TopLevelDomain.BCN -> tld.nicServer
            TopLevelDomain.BEATS -> tld.nicServer
            TopLevelDomain.BEAUTY -> tld.nicServer
            TopLevelDomain.BEER -> tld.nicServer
            TopLevelDomain.BENTLEY -> tld.nicServer
            TopLevelDomain.BERLIN -> tld.nicServer
            TopLevelDomain.BEST -> tld.nicServer
            TopLevelDomain.BESTBUY -> tld.nicServer
            TopLevelDomain.BET -> tld.nicServer
            TopLevelDomain.BHARTI -> tld.nicServer
            TopLevelDomain.BIBLE -> tld.nicServer
            TopLevelDomain.BID -> tld.nicServer
            TopLevelDomain.BIKE -> tld.nicServer
            TopLevelDomain.BING -> tld.nicServer
            TopLevelDomain.BINGO -> tld.nicServer
            TopLevelDomain.BIO -> tld.nicServer
            TopLevelDomain.BLACK -> tld.nicServer
            TopLevelDomain.BLACKFRIDAY -> tld.nicServer
            TopLevelDomain.BLOCKBUSTER -> tld.nicServer
            TopLevelDomain.BLOG -> tld.nicServer
            TopLevelDomain.BLOOMBERG -> tld.nicServer
            TopLevelDomain.BLUE -> tld.nicServer
            TopLevelDomain.BMS -> tld.nicServer
            TopLevelDomain.BMW -> tld.nicServer
            TopLevelDomain.BNPPARIBAS -> tld.nicServer
            TopLevelDomain.BOATS -> tld.nicServer
            TopLevelDomain.BOEHRINGER -> tld.nicServer
            TopLevelDomain.BOFA -> tld.nicServer
            TopLevelDomain.BOM -> tld.nicServer
            TopLevelDomain.BOND -> tld.nicServer
            TopLevelDomain.BOO -> tld.nicServer
            TopLevelDomain.BOOK -> tld.nicServer
            TopLevelDomain.BOOKING -> tld.nicServer
            TopLevelDomain.BOSCH -> tld.nicServer
            TopLevelDomain.BOSTIK -> tld.nicServer
            TopLevelDomain.BOSTON -> tld.nicServer
            TopLevelDomain.BOT -> tld.nicServer
            TopLevelDomain.BOUTIQUE -> tld.nicServer
            TopLevelDomain.BOX -> tld.nicServer
            TopLevelDomain.BRADESCO -> tld.nicServer
            TopLevelDomain.BRIDGESTONE -> tld.nicServer
            TopLevelDomain.BROADWAY -> tld.nicServer
            TopLevelDomain.BROKER -> tld.nicServer
            TopLevelDomain.BROTHER -> tld.nicServer
            TopLevelDomain.BRUSSELS -> tld.nicServer
            TopLevelDomain.BUILD -> tld.nicServer
            TopLevelDomain.BUILDERS -> tld.nicServer
            TopLevelDomain.BUSINESS -> tld.nicServer
            TopLevelDomain.BUY -> tld.nicServer
            TopLevelDomain.BUZZ -> tld.nicServer
            TopLevelDomain.BZH -> tld.nicServer
            TopLevelDomain.CAB -> tld.nicServer
            TopLevelDomain.CAFE -> tld.nicServer
            TopLevelDomain.CAL -> tld.nicServer
            TopLevelDomain.CALL -> tld.nicServer
            TopLevelDomain.CALVINKLEIN -> tld.nicServer
            TopLevelDomain.CAM -> tld.nicServer
            TopLevelDomain.CAMERA -> tld.nicServer
            TopLevelDomain.CAMP -> tld.nicServer
            TopLevelDomain.CANON -> tld.nicServer
            TopLevelDomain.CAPETOWN -> tld.nicServer
            TopLevelDomain.CAPITAL -> tld.nicServer
            TopLevelDomain.CAPITALONE -> tld.nicServer
            TopLevelDomain.CAR -> tld.nicServer
            TopLevelDomain.CARAVAN -> tld.nicServer
            TopLevelDomain.CARDS -> tld.nicServer
            TopLevelDomain.CARE -> tld.nicServer
            TopLevelDomain.CAREER -> tld.nicServer
            TopLevelDomain.CAREERS -> tld.nicServer
            TopLevelDomain.CARS -> tld.nicServer
            TopLevelDomain.CASA -> tld.nicServer
            TopLevelDomain.CASE -> tld.nicServer
            TopLevelDomain.CASH -> tld.nicServer
            TopLevelDomain.CASINO -> tld.nicServer
            TopLevelDomain.CATERING -> tld.nicServer
            TopLevelDomain.CATHOLIC -> tld.nicServer
            TopLevelDomain.CBA -> tld.nicServer
            TopLevelDomain.CBN -> tld.nicServer
            TopLevelDomain.CBRE -> tld.nicServer
            TopLevelDomain.CENTER -> tld.nicServer
            TopLevelDomain.CEO -> tld.nicServer
            TopLevelDomain.CERN -> tld.nicServer
            TopLevelDomain.CFA -> tld.nicServer
            TopLevelDomain.CFD -> tld.nicServer
            TopLevelDomain.CHANEL -> tld.nicServer
            TopLevelDomain.CHANNEL -> tld.nicServer
            TopLevelDomain.CHARITY -> tld.nicServer
            TopLevelDomain.CHASE -> tld.nicServer
            TopLevelDomain.CHAT -> tld.nicServer
            TopLevelDomain.CHEAP -> tld.nicServer
            TopLevelDomain.CHINTAI -> tld.nicServer
            TopLevelDomain.CHRISTMAS -> tld.nicServer
            TopLevelDomain.CHROME -> tld.nicServer
            TopLevelDomain.CHURCH -> tld.nicServer
            TopLevelDomain.CIPRIANI -> tld.nicServer
            TopLevelDomain.CIRCLE -> tld.nicServer
            TopLevelDomain.CISCO -> tld.nicServer
            TopLevelDomain.CITADEL -> tld.nicServer
            TopLevelDomain.CITI -> tld.nicServer
            TopLevelDomain.CITIC -> tld.nicServer
            TopLevelDomain.CITY -> tld.nicServer
            TopLevelDomain.CLAIMS -> tld.nicServer
            TopLevelDomain.CLEANING -> tld.nicServer
            TopLevelDomain.CLICK -> tld.nicServer
            TopLevelDomain.CLINIC -> tld.nicServer
            TopLevelDomain.CLINIQUE -> tld.nicServer
            TopLevelDomain.CLOTHING -> tld.nicServer
            TopLevelDomain.CLOUD -> tld.nicServer
            TopLevelDomain.CLUB -> tld.nicServer
            TopLevelDomain.CLUBMED -> tld.nicServer
            TopLevelDomain.COACH -> tld.nicServer
            TopLevelDomain.CODES -> tld.nicServer
            TopLevelDomain.COFFEE -> tld.nicServer
            TopLevelDomain.COLLEGE -> tld.nicServer
            TopLevelDomain.COLOGNE -> tld.nicServer
            TopLevelDomain.COMMBANK -> tld.nicServer
            TopLevelDomain.COMMUNITY -> tld.nicServer
            TopLevelDomain.COMPANY -> tld.nicServer
            TopLevelDomain.COMPARE -> tld.nicServer
            TopLevelDomain.COMPUTER -> tld.nicServer
            TopLevelDomain.COMSEC -> tld.nicServer
            TopLevelDomain.CONDOS -> tld.nicServer
            TopLevelDomain.CONSTRUCTION -> tld.nicServer
            TopLevelDomain.CONSULTING -> tld.nicServer
            TopLevelDomain.CONTACT -> tld.nicServer
            TopLevelDomain.CONTRACTORS -> tld.nicServer
            TopLevelDomain.COOKING -> tld.nicServer
            TopLevelDomain.COOL -> tld.nicServer
            TopLevelDomain.CORSICA -> tld.nicServer
            TopLevelDomain.COUNTRY -> tld.nicServer
            TopLevelDomain.COUPON -> tld.nicServer
            TopLevelDomain.COUPONS -> tld.nicServer
            TopLevelDomain.COURSES -> tld.nicServer
            TopLevelDomain.CPA -> tld.nicServer
            TopLevelDomain.CREDIT -> tld.nicServer
            TopLevelDomain.CREDITCARD -> tld.nicServer
            TopLevelDomain.CREDITUNION -> tld.nicServer
            TopLevelDomain.CRICKET -> tld.nicServer
            TopLevelDomain.CROWN -> tld.nicServer
            TopLevelDomain.CRS -> tld.nicServer
            TopLevelDomain.CRUISE -> tld.nicServer
            TopLevelDomain.CRUISES -> tld.nicServer
            TopLevelDomain.CUISINELLA -> tld.nicServer
            TopLevelDomain.CYMRU -> tld.nicServer
            TopLevelDomain.CYOU -> tld.nicServer
            TopLevelDomain.DABUR -> tld.nicServer
            TopLevelDomain.DAD -> tld.nicServer
            TopLevelDomain.DANCE -> tld.nicServer
            TopLevelDomain.DATA -> tld.nicServer
            TopLevelDomain.DATE -> tld.nicServer
            TopLevelDomain.DATING -> tld.nicServer
            TopLevelDomain.DATSUN -> tld.nicServer
            TopLevelDomain.DAY -> tld.nicServer
            TopLevelDomain.DCLK -> tld.nicServer
            TopLevelDomain.DDS -> tld.nicServer
            TopLevelDomain.DEAL -> tld.nicServer
            TopLevelDomain.DEALER -> tld.nicServer
            TopLevelDomain.DEALS -> tld.nicServer
            TopLevelDomain.DEGREE -> tld.nicServer
            TopLevelDomain.DELIVERY -> tld.nicServer
            TopLevelDomain.DELL -> tld.nicServer
            TopLevelDomain.DELOITTE -> tld.nicServer
            TopLevelDomain.DELTA -> tld.nicServer
            TopLevelDomain.DEMOCRAT -> tld.nicServer
            TopLevelDomain.DENTAL -> tld.nicServer
            TopLevelDomain.DENTIST -> tld.nicServer
            TopLevelDomain.DESI -> tld.nicServer
            TopLevelDomain.DESIGN -> tld.nicServer
            TopLevelDomain.DEV -> tld.nicServer
            TopLevelDomain.DHL -> tld.nicServer
            TopLevelDomain.DIAMONDS -> tld.nicServer
            TopLevelDomain.DIET -> tld.nicServer
            TopLevelDomain.DIGITAL -> tld.nicServer
            TopLevelDomain.DIRECT -> tld.nicServer
            TopLevelDomain.DIRECTORY -> tld.nicServer
            TopLevelDomain.DISCOUNT -> tld.nicServer
            TopLevelDomain.DISCOVER -> tld.nicServer
            TopLevelDomain.DISH -> tld.nicServer
            TopLevelDomain.DIY -> tld.nicServer
            TopLevelDomain.DNP -> tld.nicServer
            TopLevelDomain.DOCS -> tld.nicServer
            TopLevelDomain.DOCTOR -> tld.nicServer
            TopLevelDomain.DOG -> tld.nicServer
            TopLevelDomain.DOMAINS -> tld.nicServer
            TopLevelDomain.DOT -> tld.nicServer
            TopLevelDomain.DOWNLOAD -> tld.nicServer
            TopLevelDomain.DRIVE -> tld.nicServer
            TopLevelDomain.DTV -> tld.nicServer
            TopLevelDomain.DUBAI -> tld.nicServer
            TopLevelDomain.DUNLOP -> tld.nicServer
            TopLevelDomain.DUPONT -> tld.nicServer
            TopLevelDomain.DURBAN -> tld.nicServer
            TopLevelDomain.DVAG -> tld.nicServer
            TopLevelDomain.DVR -> tld.nicServer
            TopLevelDomain.EARTH -> tld.nicServer
            TopLevelDomain.EAT -> tld.nicServer
            TopLevelDomain.ECO -> tld.nicServer
            TopLevelDomain.EDEKA -> tld.nicServer
            TopLevelDomain.EDUCATION -> tld.nicServer
            TopLevelDomain.EMAIL -> tld.nicServer
            TopLevelDomain.EMERCK -> tld.nicServer
            TopLevelDomain.ENERGY -> tld.nicServer
            TopLevelDomain.ENGINEER -> tld.nicServer
            TopLevelDomain.ENGINEERING -> tld.nicServer
            TopLevelDomain.ENTERPRISES -> tld.nicServer
            TopLevelDomain.EPSON -> tld.nicServer
            TopLevelDomain.EQUIPMENT -> tld.nicServer
            TopLevelDomain.ERICSSON -> tld.nicServer
            TopLevelDomain.ERNI -> tld.nicServer
            TopLevelDomain.ESQ -> tld.nicServer
            TopLevelDomain.ESTATE -> tld.nicServer
            TopLevelDomain.EUROVISION -> tld.nicServer
            TopLevelDomain.EUS -> tld.nicServer
            TopLevelDomain.EVENTS -> tld.nicServer
            TopLevelDomain.EXCHANGE -> tld.nicServer
            TopLevelDomain.EXPERT -> tld.nicServer
            TopLevelDomain.EXPOSED -> tld.nicServer
            TopLevelDomain.EXPRESS -> tld.nicServer
            TopLevelDomain.EXTRASPACE -> tld.nicServer
            TopLevelDomain.FAGE -> tld.nicServer
            TopLevelDomain.FAIL -> tld.nicServer
            TopLevelDomain.FAIRWINDS -> tld.nicServer
            TopLevelDomain.FAITH -> tld.nicServer
            TopLevelDomain.FAMILY -> tld.nicServer
            TopLevelDomain.FAN -> tld.nicServer
            TopLevelDomain.FANS -> tld.nicServer
            TopLevelDomain.FARM -> tld.nicServer
            TopLevelDomain.FARMERS -> tld.nicServer
            TopLevelDomain.FASHION -> tld.nicServer
            TopLevelDomain.FAST -> tld.nicServer
            TopLevelDomain.FEDEX -> tld.nicServer
            TopLevelDomain.FEEDBACK -> tld.nicServer
            TopLevelDomain.FERRARI -> tld.nicServer
            TopLevelDomain.FERRERO -> tld.nicServer
            TopLevelDomain.FIDELITY -> tld.nicServer
            TopLevelDomain.FIDO -> tld.nicServer
            TopLevelDomain.FILM -> tld.nicServer
            TopLevelDomain.FINAL -> tld.nicServer
            TopLevelDomain.FINANCE -> tld.nicServer
            TopLevelDomain.FINANCIAL -> tld.nicServer
            TopLevelDomain.FIRE -> tld.nicServer
            TopLevelDomain.FIRESTONE -> tld.nicServer
            TopLevelDomain.FIRMDALE -> tld.nicServer
            TopLevelDomain.FISH -> tld.nicServer
            TopLevelDomain.FISHING -> tld.nicServer
            TopLevelDomain.FIT -> tld.nicServer
            TopLevelDomain.FITNESS -> tld.nicServer
            TopLevelDomain.FLICKR -> tld.nicServer
            TopLevelDomain.FLIGHTS -> tld.nicServer
            TopLevelDomain.FLIR -> tld.nicServer
            TopLevelDomain.FLORIST -> tld.nicServer
            TopLevelDomain.FLOWERS -> tld.nicServer
            TopLevelDomain.FLY -> tld.nicServer
            TopLevelDomain.FOO -> tld.nicServer
            TopLevelDomain.FOOD -> tld.nicServer
            TopLevelDomain.FOOTBALL -> tld.nicServer
            TopLevelDomain.FORD -> tld.nicServer
            TopLevelDomain.FOREX -> tld.nicServer
            TopLevelDomain.FORSALE -> tld.nicServer
            TopLevelDomain.FORUM -> tld.nicServer
            TopLevelDomain.FOUNDATION -> tld.nicServer
            TopLevelDomain.FOX -> tld.nicServer
            TopLevelDomain.FREE -> tld.nicServer
            TopLevelDomain.FRESENIUS -> tld.nicServer
            TopLevelDomain.FRL -> tld.nicServer
            TopLevelDomain.FROGANS -> tld.nicServer
            TopLevelDomain.FRONTIER -> tld.nicServer
            TopLevelDomain.FTR -> tld.nicServer
            TopLevelDomain.FUJITSU -> tld.nicServer
            TopLevelDomain.FUN -> tld.nicServer
            TopLevelDomain.FUND -> tld.nicServer
            TopLevelDomain.FURNITURE -> tld.nicServer
            TopLevelDomain.FUTBOL -> tld.nicServer
            TopLevelDomain.FYI -> tld.nicServer
            TopLevelDomain.GAL -> tld.nicServer
            TopLevelDomain.GALLERY -> tld.nicServer
            TopLevelDomain.GALLO -> tld.nicServer
            TopLevelDomain.GALLUP -> tld.nicServer
            TopLevelDomain.GAME -> tld.nicServer
            TopLevelDomain.GAMES -> tld.nicServer
            TopLevelDomain.GAP -> tld.nicServer
            TopLevelDomain.GARDEN -> tld.nicServer
            TopLevelDomain.GAY -> tld.nicServer
            TopLevelDomain.GBIZ -> tld.nicServer
            TopLevelDomain.GDN -> tld.nicServer
            TopLevelDomain.GEA -> tld.nicServer
            TopLevelDomain.GENT -> tld.nicServer
            TopLevelDomain.GENTING -> tld.nicServer
            TopLevelDomain.GEORGE -> tld.nicServer
            TopLevelDomain.GGEE -> tld.nicServer
            TopLevelDomain.GIFT -> tld.nicServer
            TopLevelDomain.GIFTS -> tld.nicServer
            TopLevelDomain.GIVES -> tld.nicServer
            TopLevelDomain.GIVING -> tld.nicServer
            TopLevelDomain.GLASS -> tld.nicServer
            TopLevelDomain.GLE -> tld.nicServer
            TopLevelDomain.GLOBAL -> tld.nicServer
            TopLevelDomain.GLOBO -> tld.nicServer
            TopLevelDomain.GMAIL -> tld.nicServer
            TopLevelDomain.GMBH -> tld.nicServer
            TopLevelDomain.GMO -> tld.nicServer
            TopLevelDomain.GMX -> tld.nicServer
            TopLevelDomain.GODADDY -> tld.nicServer
            TopLevelDomain.GOLD -> tld.nicServer
            TopLevelDomain.GOLDPOINT -> tld.nicServer
            TopLevelDomain.GOLF -> tld.nicServer
            TopLevelDomain.GOO -> tld.nicServer
            TopLevelDomain.GOODYEAR -> tld.nicServer
            TopLevelDomain.GOOG -> tld.nicServer
            TopLevelDomain.GOOGLE -> tld.nicServer
            TopLevelDomain.GOP -> tld.nicServer
            TopLevelDomain.GOT -> tld.nicServer
            TopLevelDomain.GRAINGER -> tld.nicServer
            TopLevelDomain.GRAPHICS -> tld.nicServer
            TopLevelDomain.GRATIS -> tld.nicServer
            TopLevelDomain.GREEN -> tld.nicServer
            TopLevelDomain.GRIPE -> tld.nicServer
            TopLevelDomain.GROCERY -> tld.nicServer
            TopLevelDomain.GROUP -> tld.nicServer
            TopLevelDomain.GUCCI -> tld.nicServer
            TopLevelDomain.GUGE -> tld.nicServer
            TopLevelDomain.GUIDE -> tld.nicServer
            TopLevelDomain.GUITARS -> tld.nicServer
            TopLevelDomain.GURU -> tld.nicServer
            TopLevelDomain.HAIR -> tld.nicServer
            TopLevelDomain.HAMBURG -> tld.nicServer
            TopLevelDomain.HANGOUT -> tld.nicServer
            TopLevelDomain.HAUS -> tld.nicServer
            TopLevelDomain.HBO -> tld.nicServer
            TopLevelDomain.HDFC -> tld.nicServer
            TopLevelDomain.HDFCBANK -> tld.nicServer
            TopLevelDomain.HEALTH -> tld.nicServer
            TopLevelDomain.HEALTHCARE -> tld.nicServer
            TopLevelDomain.HELP -> tld.nicServer
            TopLevelDomain.HELSINKI -> tld.nicServer
            TopLevelDomain.HERE -> tld.nicServer
            TopLevelDomain.HERMES -> tld.nicServer
            TopLevelDomain.HIPHOP -> tld.nicServer
            TopLevelDomain.HISAMITSU -> tld.nicServer
            TopLevelDomain.HITACHI -> tld.nicServer
            TopLevelDomain.HIV -> tld.nicServer
            TopLevelDomain.HKT -> tld.nicServer
            TopLevelDomain.HOCKEY -> tld.nicServer
            TopLevelDomain.HOLDINGS -> tld.nicServer
            TopLevelDomain.HOLIDAY -> tld.nicServer
            TopLevelDomain.HOMEDEPOT -> tld.nicServer
            TopLevelDomain.HOMEGOODS -> tld.nicServer
            TopLevelDomain.HOMES -> tld.nicServer
            TopLevelDomain.HOMESENSE -> tld.nicServer
            TopLevelDomain.HONDA -> tld.nicServer
            TopLevelDomain.HORSE -> tld.nicServer
            TopLevelDomain.HOSPITAL -> tld.nicServer
            TopLevelDomain.HOST -> tld.nicServer
            TopLevelDomain.HOSTING -> tld.nicServer
            TopLevelDomain.HOT -> tld.nicServer
            TopLevelDomain.HOTELS -> tld.nicServer
            TopLevelDomain.HOTMAIL -> tld.nicServer
            TopLevelDomain.HOUSE -> tld.nicServer
            TopLevelDomain.HOW -> tld.nicServer
            TopLevelDomain.HSBC -> tld.nicServer
            TopLevelDomain.HUGHES -> tld.nicServer
            TopLevelDomain.HYATT -> tld.nicServer
            TopLevelDomain.HYUNDAI -> tld.nicServer
            TopLevelDomain.IBM -> tld.nicServer
            TopLevelDomain.ICBC -> tld.nicServer
            TopLevelDomain.ICE -> tld.nicServer
            TopLevelDomain.ICU -> tld.nicServer
            TopLevelDomain.IEEE -> tld.nicServer
            TopLevelDomain.IFM -> tld.nicServer
            TopLevelDomain.IKANO -> tld.nicServer
            TopLevelDomain.IMAMAT -> tld.nicServer
            TopLevelDomain.IMDB -> tld.nicServer
            TopLevelDomain.IMMO -> tld.nicServer
            TopLevelDomain.IMMOBILIEN -> tld.nicServer
            TopLevelDomain.INC -> tld.nicServer
            TopLevelDomain.INDUSTRIES -> tld.nicServer
            TopLevelDomain.INFINITI -> tld.nicServer
            TopLevelDomain.ING -> tld.nicServer
            TopLevelDomain.INK -> tld.nicServer
            TopLevelDomain.INSTITUTE -> tld.nicServer
            TopLevelDomain.INSURANCE -> tld.nicServer
            TopLevelDomain.INSURE -> tld.nicServer
            TopLevelDomain.INTERNATIONAL -> tld.nicServer
            TopLevelDomain.INTUIT -> tld.nicServer
            TopLevelDomain.INVESTMENTS -> tld.nicServer
            TopLevelDomain.IPIRANGA -> tld.nicServer
            TopLevelDomain.IRISH -> tld.nicServer
            TopLevelDomain.ISMAILI -> tld.nicServer
            TopLevelDomain.IST -> tld.nicServer
            TopLevelDomain.ISTANBUL -> tld.nicServer
            TopLevelDomain.ITAU -> tld.nicServer
            TopLevelDomain.ITV -> tld.nicServer
            TopLevelDomain.JAGUAR -> tld.nicServer
            TopLevelDomain.JAVA -> tld.nicServer
            TopLevelDomain.JCB -> tld.nicServer
            TopLevelDomain.JEEP -> tld.nicServer
            TopLevelDomain.JETZT -> tld.nicServer
            TopLevelDomain.JEWELRY -> tld.nicServer
            TopLevelDomain.JIO -> tld.nicServer
            TopLevelDomain.JLL -> tld.nicServer
            TopLevelDomain.JMP -> tld.nicServer
            TopLevelDomain.JNJ -> tld.nicServer
            TopLevelDomain.JOBURG -> tld.nicServer
            TopLevelDomain.JOT -> tld.nicServer
            TopLevelDomain.JOY -> tld.nicServer
            TopLevelDomain.JPMORGAN -> tld.nicServer
            TopLevelDomain.JPRS -> tld.nicServer
            TopLevelDomain.JUEGOS -> tld.nicServer
            TopLevelDomain.JUNIPER -> tld.nicServer
            TopLevelDomain.KAUFEN -> tld.nicServer
            TopLevelDomain.KDDI -> tld.nicServer
            TopLevelDomain.KERRYHOTELS -> tld.nicServer
            TopLevelDomain.KERRYLOGISTICS -> tld.nicServer
            TopLevelDomain.KERRYPROPERTIES -> tld.nicServer
            TopLevelDomain.KFH -> tld.nicServer
            TopLevelDomain.KIA -> tld.nicServer
            TopLevelDomain.KIDS -> tld.nicServer
            TopLevelDomain.KIM -> tld.nicServer
            TopLevelDomain.KINDLE -> tld.nicServer
            TopLevelDomain.KITCHEN -> tld.nicServer
            TopLevelDomain.KIWI -> tld.nicServer
            TopLevelDomain.KOELN -> tld.nicServer
            TopLevelDomain.KOMATSU -> tld.nicServer
            TopLevelDomain.KOSHER -> tld.nicServer
            TopLevelDomain.KPMG -> tld.nicServer
            TopLevelDomain.KPN -> tld.nicServer
            TopLevelDomain.KRD -> tld.nicServer
            TopLevelDomain.KRED -> tld.nicServer
            TopLevelDomain.KUOKGROUP -> tld.nicServer
            TopLevelDomain.KYOTO -> tld.nicServer
            TopLevelDomain.LACAIXA -> tld.nicServer
            TopLevelDomain.LAMBORGHINI -> tld.nicServer
            TopLevelDomain.LAMER -> tld.nicServer
            TopLevelDomain.LANCASTER -> tld.nicServer
            TopLevelDomain.LAND -> tld.nicServer
            TopLevelDomain.LANDROVER -> tld.nicServer
            TopLevelDomain.LANXESS -> tld.nicServer
            TopLevelDomain.LASALLE -> tld.nicServer
            TopLevelDomain.LAT -> tld.nicServer
            TopLevelDomain.LATINO -> tld.nicServer
            TopLevelDomain.LATROBE -> tld.nicServer
            TopLevelDomain.LAW -> tld.nicServer
            TopLevelDomain.LAWYER -> tld.nicServer
            TopLevelDomain.LDS -> tld.nicServer
            TopLevelDomain.LEASE -> tld.nicServer
            TopLevelDomain.LECLERC -> tld.nicServer
            TopLevelDomain.LEFRAK -> tld.nicServer
            TopLevelDomain.LEGAL -> tld.nicServer
            TopLevelDomain.LEGO -> tld.nicServer
            TopLevelDomain.LEXUS -> tld.nicServer
            TopLevelDomain.LGBT -> tld.nicServer
            TopLevelDomain.LIDL -> tld.nicServer
            TopLevelDomain.LIFE -> tld.nicServer
            TopLevelDomain.LIFEINSURANCE -> tld.nicServer
            TopLevelDomain.LIFESTYLE -> tld.nicServer
            TopLevelDomain.LIGHTING -> tld.nicServer
            TopLevelDomain.LIKE -> tld.nicServer
            TopLevelDomain.LILLY -> tld.nicServer
            TopLevelDomain.LIMITED -> tld.nicServer
            TopLevelDomain.LIMO -> tld.nicServer
            TopLevelDomain.LINCOLN -> tld.nicServer
            TopLevelDomain.LINK -> tld.nicServer
            TopLevelDomain.LIPSY -> tld.nicServer
            TopLevelDomain.LIVE -> tld.nicServer
            TopLevelDomain.LIVING -> tld.nicServer
            TopLevelDomain.LLC -> tld.nicServer
            TopLevelDomain.LLP -> tld.nicServer
            TopLevelDomain.LOAN -> tld.nicServer
            TopLevelDomain.LOANS -> tld.nicServer
            TopLevelDomain.LOCKER -> tld.nicServer
            TopLevelDomain.LOCUS -> tld.nicServer
            TopLevelDomain.LOL -> tld.nicServer
            TopLevelDomain.LONDON -> tld.nicServer
            TopLevelDomain.LOTTE -> tld.nicServer
            TopLevelDomain.LOTTO -> tld.nicServer
            TopLevelDomain.LOVE -> tld.nicServer
            TopLevelDomain.LPL -> tld.nicServer
            TopLevelDomain.LPLFINANCIAL -> tld.nicServer
            TopLevelDomain.LTD -> tld.nicServer
            TopLevelDomain.LTDA -> tld.nicServer
            TopLevelDomain.LUNDBECK -> tld.nicServer
            TopLevelDomain.LUXE -> tld.nicServer
            TopLevelDomain.LUXURY -> tld.nicServer
            TopLevelDomain.MADRID -> tld.nicServer
            TopLevelDomain.MAIF -> tld.nicServer
            TopLevelDomain.MAISON -> tld.nicServer
            TopLevelDomain.MAKEUP -> tld.nicServer
            TopLevelDomain.MAN -> tld.nicServer
            TopLevelDomain.MANAGEMENT -> tld.nicServer
            TopLevelDomain.MANGO -> tld.nicServer
            TopLevelDomain.MAP -> tld.nicServer
            TopLevelDomain.MARKET -> tld.nicServer
            TopLevelDomain.MARKETING -> tld.nicServer
            TopLevelDomain.MARKETS -> tld.nicServer
            TopLevelDomain.MARRIOTT -> tld.nicServer
            TopLevelDomain.MARSHALLS -> tld.nicServer
            TopLevelDomain.MATTEL -> tld.nicServer
            TopLevelDomain.MBA -> tld.nicServer
            TopLevelDomain.MCKINSEY -> tld.nicServer
            TopLevelDomain.MED -> tld.nicServer
            TopLevelDomain.MEDIA -> tld.nicServer
            TopLevelDomain.MEET -> tld.nicServer
            TopLevelDomain.MELBOURNE -> tld.nicServer
            TopLevelDomain.MEME -> tld.nicServer
            TopLevelDomain.MEMORIAL -> tld.nicServer
            TopLevelDomain.MEN -> tld.nicServer
            TopLevelDomain.MENU -> tld.nicServer
            TopLevelDomain.MERCKMSD -> tld.nicServer
            TopLevelDomain.MIAMI -> tld.nicServer
            TopLevelDomain.MICROSOFT -> tld.nicServer
            TopLevelDomain.MINI -> tld.nicServer
            TopLevelDomain.MINT -> tld.nicServer
            TopLevelDomain.MIT -> tld.nicServer
            TopLevelDomain.MITSUBISHI -> tld.nicServer
            TopLevelDomain.MLB -> tld.nicServer
            TopLevelDomain.MLS -> tld.nicServer
            TopLevelDomain.MMA -> tld.nicServer
            TopLevelDomain.MOBILE -> tld.nicServer
            TopLevelDomain.MODA -> tld.nicServer
            TopLevelDomain.MOE -> tld.nicServer
            TopLevelDomain.MOI -> tld.nicServer
            TopLevelDomain.MOM -> tld.nicServer
            TopLevelDomain.MONASH -> tld.nicServer
            TopLevelDomain.MONEY -> tld.nicServer
            TopLevelDomain.MONSTER -> tld.nicServer
            TopLevelDomain.MORMON -> tld.nicServer
            TopLevelDomain.MORTGAGE -> tld.nicServer
            TopLevelDomain.MOSCOW -> tld.nicServer
            TopLevelDomain.MOTO -> tld.nicServer
            TopLevelDomain.MOTORCYCLES -> tld.nicServer
            TopLevelDomain.MOV -> tld.nicServer
            TopLevelDomain.MOVIE -> tld.nicServer
            TopLevelDomain.MSD -> tld.nicServer
            TopLevelDomain.MTN -> tld.nicServer
            TopLevelDomain.MTR -> tld.nicServer
            TopLevelDomain.MUSIC -> tld.nicServer
            TopLevelDomain.NAB -> tld.nicServer
            TopLevelDomain.NAGOYA -> tld.nicServer
            TopLevelDomain.NATURA -> tld.nicServer
            TopLevelDomain.NAVY -> tld.nicServer
            TopLevelDomain.NBA -> tld.nicServer
            TopLevelDomain.NEC -> tld.nicServer
            TopLevelDomain.NETBANK -> tld.nicServer
            TopLevelDomain.NETFLIX -> tld.nicServer
            TopLevelDomain.NETWORK -> tld.nicServer
            TopLevelDomain.NEUSTAR -> tld.nicServer
            TopLevelDomain.NEW -> tld.nicServer
            TopLevelDomain.NEWS -> tld.nicServer
            TopLevelDomain.NEXT -> tld.nicServer
            TopLevelDomain.NEXTDIRECT -> tld.nicServer
            TopLevelDomain.NEXUS -> tld.nicServer
            TopLevelDomain.NFL -> tld.nicServer
            TopLevelDomain.NGO -> tld.nicServer
            TopLevelDomain.NHK -> tld.nicServer
            TopLevelDomain.NICO -> tld.nicServer
            TopLevelDomain.NIKE -> tld.nicServer
            TopLevelDomain.NIKON -> tld.nicServer
            TopLevelDomain.NINJA -> tld.nicServer
            TopLevelDomain.NISSAN -> tld.nicServer
            TopLevelDomain.NISSAY -> tld.nicServer
            TopLevelDomain.NOKIA -> tld.nicServer
            TopLevelDomain.NORTON -> tld.nicServer
            TopLevelDomain.NOW -> tld.nicServer
            TopLevelDomain.NOWRUZ -> tld.nicServer
            TopLevelDomain.NOWTV -> tld.nicServer
            TopLevelDomain.NRA -> tld.nicServer
            TopLevelDomain.NRW -> tld.nicServer
            TopLevelDomain.NTT -> tld.nicServer
            TopLevelDomain.NYC -> tld.nicServer
            TopLevelDomain.OBI -> tld.nicServer
            TopLevelDomain.OBSERVER -> tld.nicServer
            TopLevelDomain.OFFICE -> tld.nicServer
            TopLevelDomain.OKINAWA -> tld.nicServer
            TopLevelDomain.OLAYAN -> tld.nicServer
            TopLevelDomain.OLAYANGROUP -> tld.nicServer
            TopLevelDomain.OLLO -> tld.nicServer
            TopLevelDomain.OMEGA -> tld.nicServer
            TopLevelDomain.ONE -> tld.nicServer
            TopLevelDomain.ONG -> tld.nicServer
            TopLevelDomain.ONL -> tld.nicServer
            TopLevelDomain.ONLINE -> tld.nicServer
            TopLevelDomain.OOO -> tld.nicServer
            TopLevelDomain.OPEN -> tld.nicServer
            TopLevelDomain.ORACLE -> tld.nicServer
            TopLevelDomain.ORANGE -> tld.nicServer
            TopLevelDomain.ORGANIC -> tld.nicServer
            TopLevelDomain.ORIGINS -> tld.nicServer
            TopLevelDomain.OSAKA -> tld.nicServer
            TopLevelDomain.OTSUKA -> tld.nicServer
            TopLevelDomain.OTT -> tld.nicServer
            TopLevelDomain.OVH -> tld.nicServer
            TopLevelDomain.PAGE -> tld.nicServer
            TopLevelDomain.PANASONIC -> tld.nicServer
            TopLevelDomain.PARIS -> tld.nicServer
            TopLevelDomain.PARS -> tld.nicServer
            TopLevelDomain.PARTNERS -> tld.nicServer
            TopLevelDomain.PARTS -> tld.nicServer
            TopLevelDomain.PARTY -> tld.nicServer
            TopLevelDomain.PAY -> tld.nicServer
            TopLevelDomain.PCCW -> tld.nicServer
            TopLevelDomain.PET -> tld.nicServer
            TopLevelDomain.PFIZER -> tld.nicServer
            TopLevelDomain.PHARMACY -> tld.nicServer
            TopLevelDomain.PHD -> tld.nicServer
            TopLevelDomain.PHILIPS -> tld.nicServer
            TopLevelDomain.PHONE -> tld.nicServer
            TopLevelDomain.PHOTO -> tld.nicServer
            TopLevelDomain.PHOTOGRAPHY -> tld.nicServer
            TopLevelDomain.PHOTOS -> tld.nicServer
            TopLevelDomain.PHYSIO -> tld.nicServer
            TopLevelDomain.PICS -> tld.nicServer
            TopLevelDomain.PICTET -> tld.nicServer
            TopLevelDomain.PICTURES -> tld.nicServer
            TopLevelDomain.PID -> tld.nicServer
            TopLevelDomain.PIN -> tld.nicServer
            TopLevelDomain.PING -> tld.nicServer
            TopLevelDomain.PINK -> tld.nicServer
            TopLevelDomain.PIONEER -> tld.nicServer
            TopLevelDomain.PIZZA -> tld.nicServer
            TopLevelDomain.PLACE -> tld.nicServer
            TopLevelDomain.PLAY -> tld.nicServer
            TopLevelDomain.PLAYSTATION -> tld.nicServer
            TopLevelDomain.PLUMBING -> tld.nicServer
            TopLevelDomain.PLUS -> tld.nicServer
            TopLevelDomain.PNC -> tld.nicServer
            TopLevelDomain.POHL -> tld.nicServer
            TopLevelDomain.POKER -> tld.nicServer
            TopLevelDomain.POLITIE -> tld.nicServer
            TopLevelDomain.PORN -> tld.nicServer
            TopLevelDomain.PRAMERICA -> tld.nicServer
            TopLevelDomain.PRAXI -> tld.nicServer
            TopLevelDomain.PRESS -> tld.nicServer
            TopLevelDomain.PRIME -> tld.nicServer
            TopLevelDomain.PROD -> tld.nicServer
            TopLevelDomain.PRODUCTIONS -> tld.nicServer
            TopLevelDomain.PROF -> tld.nicServer
            TopLevelDomain.PROGRESSIVE -> tld.nicServer
            TopLevelDomain.PROMO -> tld.nicServer
            TopLevelDomain.PROPERTIES -> tld.nicServer
            TopLevelDomain.PROPERTY -> tld.nicServer
            TopLevelDomain.PROTECTION -> tld.nicServer
            TopLevelDomain.PRU -> tld.nicServer
            TopLevelDomain.PRUDENTIAL -> tld.nicServer
            TopLevelDomain.PUB -> tld.nicServer
            TopLevelDomain.PWC -> tld.nicServer
            TopLevelDomain.QPON -> tld.nicServer
            TopLevelDomain.QUEBEC -> tld.nicServer
            TopLevelDomain.QUEST -> tld.nicServer
            TopLevelDomain.RACING -> tld.nicServer
            TopLevelDomain.RADIO -> tld.nicServer
            TopLevelDomain.READ -> tld.nicServer
            TopLevelDomain.REALESTATE -> tld.nicServer
            TopLevelDomain.REALTOR -> tld.nicServer
            TopLevelDomain.REALTY -> tld.nicServer
            TopLevelDomain.RECIPES -> tld.nicServer
            TopLevelDomain.RED -> tld.nicServer
            TopLevelDomain.REDSTONE -> tld.nicServer
            TopLevelDomain.REDUMBRELLA -> tld.nicServer
            TopLevelDomain.REHAB -> tld.nicServer
            TopLevelDomain.REISE -> tld.nicServer
            TopLevelDomain.REISEN -> tld.nicServer
            TopLevelDomain.REIT -> tld.nicServer
            TopLevelDomain.RELIANCE -> tld.nicServer
            TopLevelDomain.REN -> tld.nicServer
            TopLevelDomain.RENT -> tld.nicServer
            TopLevelDomain.RENTALS -> tld.nicServer
            TopLevelDomain.REPAIR -> tld.nicServer
            TopLevelDomain.REPORT -> tld.nicServer
            TopLevelDomain.REPUBLICAN -> tld.nicServer
            TopLevelDomain.REST -> tld.nicServer
            TopLevelDomain.RESTAURANT -> tld.nicServer
            TopLevelDomain.REVIEW -> tld.nicServer
            TopLevelDomain.REVIEWS -> tld.nicServer
            TopLevelDomain.REXROTH -> tld.nicServer
            TopLevelDomain.RICH -> tld.nicServer
            TopLevelDomain.RICHARDLI -> tld.nicServer
            TopLevelDomain.RICOH -> tld.nicServer
            TopLevelDomain.RIL -> tld.nicServer
            TopLevelDomain.RIO -> tld.nicServer
            TopLevelDomain.RIP -> tld.nicServer
            TopLevelDomain.ROCKS -> tld.nicServer
            TopLevelDomain.RODEO -> tld.nicServer
            TopLevelDomain.ROGERS -> tld.nicServer
            TopLevelDomain.ROOM -> tld.nicServer
            TopLevelDomain.RSVP -> tld.nicServer
            TopLevelDomain.RUGBY -> tld.nicServer
            TopLevelDomain.RUHR -> tld.nicServer
            TopLevelDomain.RUN -> tld.nicServer
            TopLevelDomain.RWE -> tld.nicServer
            TopLevelDomain.RYUKYU -> tld.nicServer
            TopLevelDomain.SAARLAND -> tld.nicServer
            TopLevelDomain.SAFE -> tld.nicServer
            TopLevelDomain.SAFETY -> tld.nicServer
            TopLevelDomain.SAKURA -> tld.nicServer
            TopLevelDomain.SALE -> tld.nicServer
            TopLevelDomain.SALON -> tld.nicServer
            TopLevelDomain.SAMSCLUB -> tld.nicServer
            TopLevelDomain.SAMSUNG -> tld.nicServer
            TopLevelDomain.SANDVIK -> tld.nicServer
            TopLevelDomain.SANDVIKCOROMANT -> tld.nicServer
            TopLevelDomain.SANOFI -> tld.nicServer
            TopLevelDomain.SAP -> tld.nicServer
            TopLevelDomain.SARL -> tld.nicServer
            TopLevelDomain.SAS -> tld.nicServer
            TopLevelDomain.SAVE -> tld.nicServer
            TopLevelDomain.SAXO -> tld.nicServer
            TopLevelDomain.SBI -> tld.nicServer
            TopLevelDomain.SBS -> tld.nicServer
            TopLevelDomain.SCB -> tld.nicServer
            TopLevelDomain.SCHAEFFLER -> tld.nicServer
            TopLevelDomain.SCHMIDT -> tld.nicServer
            TopLevelDomain.SCHOLARSHIPS -> tld.nicServer
            TopLevelDomain.SCHOOL -> tld.nicServer
            TopLevelDomain.SCHULE -> tld.nicServer
            TopLevelDomain.SCHWARZ -> tld.nicServer
            TopLevelDomain.SCIENCE -> tld.nicServer
            TopLevelDomain.SCOT -> tld.nicServer
            TopLevelDomain.SEARCH -> tld.nicServer
            TopLevelDomain.SEAT -> tld.nicServer
            TopLevelDomain.SECURE -> tld.nicServer
            TopLevelDomain.SECURITY -> tld.nicServer
            TopLevelDomain.SEEK -> tld.nicServer
            TopLevelDomain.SELECT -> tld.nicServer
            TopLevelDomain.SENER -> tld.nicServer
            TopLevelDomain.SERVICES -> tld.nicServer
            TopLevelDomain.SEVEN -> tld.nicServer
            TopLevelDomain.SEW -> tld.nicServer
            TopLevelDomain.SEX -> tld.nicServer
            TopLevelDomain.SEXY -> tld.nicServer
            TopLevelDomain.SFR -> tld.nicServer
            TopLevelDomain.SHANGRILA -> tld.nicServer
            TopLevelDomain.SHARP -> tld.nicServer
            TopLevelDomain.SHAW -> tld.nicServer
            TopLevelDomain.SHELL -> tld.nicServer
            TopLevelDomain.SHIA -> tld.nicServer
            TopLevelDomain.SHIKSHA -> tld.nicServer
            TopLevelDomain.SHOES -> tld.nicServer
            TopLevelDomain.SHOP -> tld.nicServer
            TopLevelDomain.SHOPPING -> tld.nicServer
            TopLevelDomain.SHOUJI -> tld.nicServer
            TopLevelDomain.SHOW -> tld.nicServer
            TopLevelDomain.SILK -> tld.nicServer
            TopLevelDomain.SINA -> tld.nicServer
            TopLevelDomain.SINGLES -> tld.nicServer
            TopLevelDomain.SITE -> tld.nicServer
            TopLevelDomain.SKI -> tld.nicServer
            TopLevelDomain.SKIN -> tld.nicServer
            TopLevelDomain.SKY -> tld.nicServer
            TopLevelDomain.SKYPE -> tld.nicServer
            TopLevelDomain.SLING -> tld.nicServer
            TopLevelDomain.SMART -> tld.nicServer
            TopLevelDomain.SMILE -> tld.nicServer
            TopLevelDomain.SNCF -> tld.nicServer
            TopLevelDomain.SOCCER -> tld.nicServer
            TopLevelDomain.SOCIAL -> tld.nicServer
            TopLevelDomain.SOFTBANK -> tld.nicServer
            TopLevelDomain.SOFTWARE -> tld.nicServer
            TopLevelDomain.SOHU -> tld.nicServer
            TopLevelDomain.SOLAR -> tld.nicServer
            TopLevelDomain.SOLUTIONS -> tld.nicServer
            TopLevelDomain.SONG -> tld.nicServer
            TopLevelDomain.SONY -> tld.nicServer
            TopLevelDomain.SOY -> tld.nicServer
            TopLevelDomain.SPA -> tld.nicServer
            TopLevelDomain.SPACE -> tld.nicServer
            TopLevelDomain.SPORT -> tld.nicServer
            TopLevelDomain.SPOT -> tld.nicServer
            TopLevelDomain.SRL -> tld.nicServer
            TopLevelDomain.STADA -> tld.nicServer
            TopLevelDomain.STAPLES -> tld.nicServer
            TopLevelDomain.STAR -> tld.nicServer
            TopLevelDomain.STATEBANK -> tld.nicServer
            TopLevelDomain.STATEFARM -> tld.nicServer
            TopLevelDomain.STC -> tld.nicServer
            TopLevelDomain.STCGROUP -> tld.nicServer
            TopLevelDomain.STOCKHOLM -> tld.nicServer
            TopLevelDomain.STORAGE -> tld.nicServer
            TopLevelDomain.STORE -> tld.nicServer
            TopLevelDomain.STREAM -> tld.nicServer
            TopLevelDomain.STUDIO -> tld.nicServer
            TopLevelDomain.STUDY -> tld.nicServer
            TopLevelDomain.STYLE -> tld.nicServer
            TopLevelDomain.SUCKS -> tld.nicServer
            TopLevelDomain.SUPPLIES -> tld.nicServer
            TopLevelDomain.SUPPLY -> tld.nicServer
            TopLevelDomain.SUPPORT -> tld.nicServer
            TopLevelDomain.SURF -> tld.nicServer
            TopLevelDomain.SURGERY -> tld.nicServer
            TopLevelDomain.SUZUKI -> tld.nicServer
            TopLevelDomain.SWATCH -> tld.nicServer
            TopLevelDomain.SWISS -> tld.nicServer
            TopLevelDomain.SYDNEY -> tld.nicServer
            TopLevelDomain.SYSTEMS -> tld.nicServer
            TopLevelDomain.TAB -> tld.nicServer
            TopLevelDomain.TAIPEI -> tld.nicServer
            TopLevelDomain.TALK -> tld.nicServer
            TopLevelDomain.TAOBAO -> tld.nicServer
            TopLevelDomain.TARGET -> tld.nicServer
            TopLevelDomain.TATAMOTORS -> tld.nicServer
            TopLevelDomain.TATAR -> tld.nicServer
            TopLevelDomain.TATTOO -> tld.nicServer
            TopLevelDomain.TAX -> tld.nicServer
            TopLevelDomain.TAXI -> tld.nicServer
            TopLevelDomain.TCI -> tld.nicServer
            TopLevelDomain.TDK -> tld.nicServer
            TopLevelDomain.TEAM -> tld.nicServer
            TopLevelDomain.TECH -> tld.nicServer
            TopLevelDomain.TECHNOLOGY -> tld.nicServer
            TopLevelDomain.TEMASEK -> tld.nicServer
            TopLevelDomain.TENNIS -> tld.nicServer
            TopLevelDomain.TEVA -> tld.nicServer
            TopLevelDomain.THD -> tld.nicServer
            TopLevelDomain.THEATER -> tld.nicServer
            TopLevelDomain.THEATRE -> tld.nicServer
            TopLevelDomain.TIAA -> tld.nicServer
            TopLevelDomain.TICKETS -> tld.nicServer
            TopLevelDomain.TIENDA -> tld.nicServer
            TopLevelDomain.TIPS -> tld.nicServer
            TopLevelDomain.TIRES -> tld.nicServer
            TopLevelDomain.TIROL -> tld.nicServer
            TopLevelDomain.TJMAXX -> tld.nicServer
            TopLevelDomain.TJX -> tld.nicServer
            TopLevelDomain.TKMAXX -> tld.nicServer
            TopLevelDomain.TMALL -> tld.nicServer
            TopLevelDomain.TODAY -> tld.nicServer
            TopLevelDomain.TOKYO -> tld.nicServer
            TopLevelDomain.TOOLS -> tld.nicServer
            TopLevelDomain.TOP -> tld.nicServer
            TopLevelDomain.TORAY -> tld.nicServer
            TopLevelDomain.TOSHIBA -> tld.nicServer
            TopLevelDomain.TOTAL -> tld.nicServer
            TopLevelDomain.TOURS -> tld.nicServer
            TopLevelDomain.TOWN -> tld.nicServer
            TopLevelDomain.TOYOTA -> tld.nicServer
            TopLevelDomain.TOYS -> tld.nicServer
            TopLevelDomain.TRADE -> tld.nicServer
            TopLevelDomain.TRADING -> tld.nicServer
            TopLevelDomain.TRAINING -> tld.nicServer
            TopLevelDomain.TRAVELERS -> tld.nicServer
            TopLevelDomain.TRAVELERSINSURANCE -> tld.nicServer
            TopLevelDomain.TRUST -> tld.nicServer
            TopLevelDomain.TRV -> tld.nicServer
            TopLevelDomain.TUBE -> tld.nicServer
            TopLevelDomain.TUI -> tld.nicServer
            TopLevelDomain.TUNES -> tld.nicServer
            TopLevelDomain.TUSHU -> tld.nicServer
            TopLevelDomain.TVS -> tld.nicServer
            TopLevelDomain.UBANK -> tld.nicServer
            TopLevelDomain.UBS -> tld.nicServer
            TopLevelDomain.UNICOM -> tld.nicServer
            TopLevelDomain.UNIVERSITY -> tld.nicServer
            TopLevelDomain.UNO -> tld.nicServer
            TopLevelDomain.UOL -> tld.nicServer
            TopLevelDomain.UPS -> tld.nicServer
            TopLevelDomain.VACATIONS -> tld.nicServer
            TopLevelDomain.VANA -> tld.nicServer
            TopLevelDomain.VANGUARD -> tld.nicServer
            TopLevelDomain.VEGAS -> tld.nicServer
            TopLevelDomain.VENTURES -> tld.nicServer
            TopLevelDomain.VERISIGN -> tld.nicServer
            TopLevelDomain.VERSICHERUNG -> tld.nicServer
            TopLevelDomain.VET -> tld.nicServer
            TopLevelDomain.VIAJES -> tld.nicServer
            TopLevelDomain.VIDEO -> tld.nicServer
            TopLevelDomain.VIG -> tld.nicServer
            TopLevelDomain.VIKING -> tld.nicServer
            TopLevelDomain.VILLAS -> tld.nicServer
            TopLevelDomain.VIN -> tld.nicServer
            TopLevelDomain.VIP -> tld.nicServer
            TopLevelDomain.VIRGIN -> tld.nicServer
            TopLevelDomain.VISA -> tld.nicServer
            TopLevelDomain.VISION -> tld.nicServer
            TopLevelDomain.VIVA -> tld.nicServer
            TopLevelDomain.VIVO -> tld.nicServer
            TopLevelDomain.VLAANDEREN -> tld.nicServer
            TopLevelDomain.VODKA -> tld.nicServer
            TopLevelDomain.VOLVO -> tld.nicServer
            TopLevelDomain.VOTE -> tld.nicServer
            TopLevelDomain.VOTING -> tld.nicServer
            TopLevelDomain.VOTO -> tld.nicServer
            TopLevelDomain.VOYAGE -> tld.nicServer
            TopLevelDomain.WALES -> tld.nicServer
            TopLevelDomain.WALMART -> tld.nicServer
            TopLevelDomain.WALTER -> tld.nicServer
            TopLevelDomain.WANG -> tld.nicServer
            TopLevelDomain.WANGGOU -> tld.nicServer
            TopLevelDomain.WATCH -> tld.nicServer
            TopLevelDomain.WATCHES -> tld.nicServer
            TopLevelDomain.WEATHER -> tld.nicServer
            TopLevelDomain.WEATHERCHANNEL -> tld.nicServer
            TopLevelDomain.WEBCAM -> tld.nicServer
            TopLevelDomain.WEBER -> tld.nicServer
            TopLevelDomain.WEBSITE -> tld.nicServer
            TopLevelDomain.WED -> tld.nicServer
            TopLevelDomain.WEDDING -> tld.nicServer
            TopLevelDomain.WEIBO -> tld.nicServer
            TopLevelDomain.WEIR -> tld.nicServer
            TopLevelDomain.WHOSWHO -> tld.nicServer
            TopLevelDomain.WIEN -> tld.nicServer
            TopLevelDomain.WIKI -> tld.nicServer
            TopLevelDomain.WILLIAMHILL -> tld.nicServer
            TopLevelDomain.WIN -> tld.nicServer
            TopLevelDomain.WINDOWS -> tld.nicServer
            TopLevelDomain.WINE -> tld.nicServer
            TopLevelDomain.WINNERS -> tld.nicServer
            TopLevelDomain.WME -> tld.nicServer
            TopLevelDomain.WOLTERSKLUWER -> tld.nicServer
            TopLevelDomain.WOODSIDE -> tld.nicServer
            TopLevelDomain.WORK -> tld.nicServer
            TopLevelDomain.WORKS -> tld.nicServer
            TopLevelDomain.WORLD -> tld.nicServer
            TopLevelDomain.WOW -> tld.nicServer
            TopLevelDomain.WTC -> tld.nicServer
            TopLevelDomain.WTF -> tld.nicServer
            TopLevelDomain.XBOX -> tld.nicServer
            TopLevelDomain.XEROX -> tld.nicServer
            TopLevelDomain.XIHUAN -> tld.nicServer
            TopLevelDomain.XIN -> tld.nicServer
            TopLevelDomain.XN__11B4C3D -> tld.nicServer
            TopLevelDomain.XN__1CK2E1B -> tld.nicServer
            TopLevelDomain.XN__1QQW23A -> tld.nicServer
            TopLevelDomain.XN__30RR7Y -> tld.nicServer
            TopLevelDomain.XN__3BST00M -> tld.nicServer
            TopLevelDomain.XN__3DS443G -> tld.nicServer
            TopLevelDomain.XN__3PXU8K -> tld.nicServer
            TopLevelDomain.XN__42C2D9A -> tld.nicServer
            TopLevelDomain.XN__45Q11C -> tld.nicServer
            TopLevelDomain.XN__4GBRIM -> tld.nicServer
            TopLevelDomain.XN__55QW42G -> tld.nicServer
            TopLevelDomain.XN__55QX5D -> tld.nicServer
            TopLevelDomain.XN__5SU34J936BGSG -> tld.nicServer
            TopLevelDomain.XN__5TZM5G -> tld.nicServer
            TopLevelDomain.XN__6FRZ82G -> tld.nicServer
            TopLevelDomain.XN__6QQ986B3XL -> tld.nicServer
            TopLevelDomain.XN__80ADXHKS -> tld.nicServer
            TopLevelDomain.XN__80AQECDR1A -> tld.nicServer
            TopLevelDomain.XN__80ASEHDB -> tld.nicServer
            TopLevelDomain.XN__80ASWG -> tld.nicServer
            TopLevelDomain.XN__8Y0A063A -> tld.nicServer
            TopLevelDomain.XN__9DBQ2A -> tld.nicServer
            TopLevelDomain.XN__9ET52U -> tld.nicServer
            TopLevelDomain.XN__9KRT00A -> tld.nicServer
            TopLevelDomain.XN__B4W605FERD -> tld.nicServer
            TopLevelDomain.XN__BCK1B9A5DRE4C -> tld.nicServer
            TopLevelDomain.XN__C1AVG -> tld.nicServer
            TopLevelDomain.XN__C2BR7G -> tld.nicServer
            TopLevelDomain.XN__CCK2B3B -> tld.nicServer
            TopLevelDomain.XN__CCKWCXETD -> tld.nicServer
            TopLevelDomain.XN__CG4BKI -> tld.nicServer
            TopLevelDomain.XN__CZR694B -> tld.nicServer
            TopLevelDomain.XN__CZRS0T -> tld.nicServer
            TopLevelDomain.XN__CZRU2D -> tld.nicServer
            TopLevelDomain.XN__D1ACJ3B -> tld.nicServer
            TopLevelDomain.XN__ECKVDTC9D -> tld.nicServer
            TopLevelDomain.XN__EFVY88H -> tld.nicServer
            TopLevelDomain.XN__FCT429K -> tld.nicServer
            TopLevelDomain.XN__FHBEI -> tld.nicServer
            TopLevelDomain.XN__FIQ228C5HS -> tld.nicServer
            TopLevelDomain.XN__FIQ64B -> tld.nicServer
            TopLevelDomain.XN__FJQ720A -> tld.nicServer
            TopLevelDomain.XN__FLW351E -> tld.nicServer
            TopLevelDomain.XN__FZYS8D69UVGM -> tld.nicServer
            TopLevelDomain.XN__G2XX48C -> tld.nicServer
            TopLevelDomain.XN__GCKR3F0F -> tld.nicServer
            TopLevelDomain.XN__GK3AT1E -> tld.nicServer
            TopLevelDomain.XN__HXT814E -> tld.nicServer
            TopLevelDomain.XN__I1B6B1A6A2E -> tld.nicServer
            TopLevelDomain.XN__IMR513N -> tld.nicServer
            TopLevelDomain.XN__IO0A7I -> tld.nicServer
            TopLevelDomain.XN__J1AEF -> tld.nicServer
            TopLevelDomain.XN__JLQ480N2RG -> tld.nicServer
            TopLevelDomain.XN__JVR189M -> tld.nicServer
            TopLevelDomain.XN__KCRX77D1X4A -> tld.nicServer
            TopLevelDomain.XN__KPUT3I -> tld.nicServer
            TopLevelDomain.XN__MGBA3A3EJT -> tld.nicServer
            TopLevelDomain.XN__MGBA7C0BBN0A -> tld.nicServer
            TopLevelDomain.XN__MGBAB2BD -> tld.nicServer
            TopLevelDomain.XN__MGBCA7DZDO -> tld.nicServer
            TopLevelDomain.XN__MGBI4ECEXP -> tld.nicServer
            TopLevelDomain.XN__MGBT3DHD -> tld.nicServer
            TopLevelDomain.XN__MK1BU44C -> tld.nicServer
            TopLevelDomain.XN__MXTQ1M -> tld.nicServer
            TopLevelDomain.XN__NGBC5AZD -> tld.nicServer
            TopLevelDomain.XN__NGBE9E0A -> tld.nicServer
            TopLevelDomain.XN__NGBRX -> tld.nicServer
            TopLevelDomain.XN__NQV7F -> tld.nicServer
            TopLevelDomain.XN__NQV7FS00EMA -> tld.nicServer
            TopLevelDomain.XN__NYQY26A -> tld.nicServer
            TopLevelDomain.XN__OTU796D -> tld.nicServer
            TopLevelDomain.XN__P1ACF -> tld.nicServer
            TopLevelDomain.XN__PSSY2U -> tld.nicServer
            TopLevelDomain.XN__Q9JYB4C -> tld.nicServer
            TopLevelDomain.XN__QCKA1PMC -> tld.nicServer
            TopLevelDomain.XN__RHQV96G -> tld.nicServer
            TopLevelDomain.XN__ROVU88B -> tld.nicServer
            TopLevelDomain.XN__SES554G -> tld.nicServer
            TopLevelDomain.XN__T60B56A -> tld.nicServer
            TopLevelDomain.XN__TCKWE -> tld.nicServer
            TopLevelDomain.XN__TIQ49XQYJ -> tld.nicServer
            TopLevelDomain.XN__UNUP4Y -> tld.nicServer
            TopLevelDomain.XN__VERMGENSBERATER_CTB -> tld.nicServer
            TopLevelDomain.XN__VERMGENSBERATUNG_PWB -> tld.nicServer
            TopLevelDomain.XN__VHQUV -> tld.nicServer
            TopLevelDomain.XN__VUQ861B -> tld.nicServer
            TopLevelDomain.XN__W4R85EL8FHU5DNRA -> tld.nicServer
            TopLevelDomain.XN__W4RS40L -> tld.nicServer
            TopLevelDomain.XN__XHQ521B -> tld.nicServer
            TopLevelDomain.XN__ZFR164B -> tld.nicServer
            TopLevelDomain.XYZ -> tld.nicServer
            TopLevelDomain.YACHTS -> tld.nicServer
            TopLevelDomain.YAHOO -> tld.nicServer
            TopLevelDomain.YAMAXUN -> tld.nicServer
            TopLevelDomain.YANDEX -> tld.nicServer
            TopLevelDomain.YODOBASHI -> tld.nicServer
            TopLevelDomain.YOGA -> tld.nicServer
            TopLevelDomain.YOKOHAMA -> tld.nicServer
            TopLevelDomain.YOU -> tld.nicServer
            TopLevelDomain.YOUTUBE -> tld.nicServer
            TopLevelDomain.YUN -> tld.nicServer
            TopLevelDomain.ZAPPOS -> tld.nicServer
            TopLevelDomain.ZARA -> tld.nicServer
            TopLevelDomain.ZERO -> tld.nicServer
            TopLevelDomain.ZIP -> tld.nicServer
            TopLevelDomain.ZONE -> tld.nicServer
            TopLevelDomain.ZUERICH -> tld.nicServer
        }
        return ""
    }
}